Clean-up go-common for v1 release
mdblp/go-common pull request #26
Opened 2021-07-29 09:03 UTC by yvon-dblg

- Change package name to github.com/mdblp/go-common
- Remove unused code
- Remove seagull GetPrivatePair(): Not implemented
- Remove client builder, and use a much simpler approach
- Add Dockerfile to ease local dev tests
- Add test coverage report
- Update README

2021-08-02 17:40 UTC, ydrisR reviewed
Globaly ok with the proposol but we should not change the name of the client interface to API. It's better to keep consistency. 
Also, how will these types and builders modification impact the other sevices (using these clients) ?

2021-08-02 17:40 UTC, ydrisR commented on clients/opa/opa.go
> +type API interface {
Why changing the name of the type? It's called Client in all our services' clients...

2021-08-11 07:20 UTC, CedricPerotto requested changes

2021-08-11 07:20 UTC, CedricPerotto commented on clients/seagull/seagull.go
> +	}, nil
```suggestion
	return NewClient(httpClient, host)
```

2021-08-11 07:20 UTC, CedricPerotto commented on Dockerfile.test
> +ENV GO_ARCHIVE go1.16.6.linux-amd64.tar.gz
we use GO 1.16 in tests but GO 1.15 in the module... Just keep one version

2021-08-11 07:20 UTC, CedricPerotto commented on CHANGELOG.md
> +## Unreleased
Let's bump a release

2021-08-11 08:28 UTC, yvon-dblg commented on Dockerfile.test
> +ENV GO_ARCHIVE go1.16.6.linux-amd64.tar.gz
This file is just for local testing, not use in Jenkins.
To see if it keeps working on the next version

2021-08-11 09:49 UTC, CedricPerotto approved these changes

2021-08-11 09:49 UTC, merged