Publish the version of the service in the status object
mdblp/go-common pull request #7
Opened 2019-10-14 13:41 UTC by ydrisR

Modify the common object "Status" to add the version of the service.
Also add unit tests to prevent regressions

2019-10-15 16:02 UTC, CedricPerotto requested changes

2019-10-15 16:02 UTC, CedricPerotto commented on clients/status/status.go
If we don't want to embed the Version in all status struct (error status for ex.). We could Extend the Status struct only for API status.

i.e. 
```
type StatusApi struct{
	Status 
	Version string `json:"version"`
}
```
with the factory function NewStatusApi 
```
func NewStatusApi(status Status) StatusApi {
	s := StatusApi{Status : status, Version: version.Long()}
	return s
}
```
The NewStatusApi  would be only called for api.GetStatus calls.

2019-10-15 18:55 UTC, ydrisR commented on clients/status/status.go
👍

2019-10-17 14:06 UTC, BigFab reviewed
LGTM although I would like to see some more comments that I suggested inline

2019-10-17 14:06 UTC, BigFab commented on clients/version/version.go
> +	ShortCommit   string
```suggestion
	ShortCommit   string //Short commit id. i.e. 048a8d4
```

2019-10-17 14:06 UTC, BigFab commented on clients/version/version.go
> +	once.Do(func() {
```suggestion
        //Ensure this is called once so version instance is created as a singleton
	once.Do(func() {
```

2019-10-17 14:06 UTC, BigFab commented on clients/version/version.go
> +// Variables to be injected at build time
```suggestion
// Variables to be injected at build time
// E.g. go build -ldflags "-X $GO_COMMON_PATH/clients/version.ReleaseNumber=$VERSION"
```

2019-10-17 16:37 UTC, BigFab approved these changes
LGTM now :)

2019-10-18 06:45 UTC, CedricPerotto approved these changes

2019-10-18 06:47 UTC, merged